name: flutter test
on: [push]
jobs:
  mac:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - working-directory: flutter_app
        run: flutter build macos  && ls build/macos/Build/Products/Release/


  win:
    runs-on: windows-latest
    env:
      WINDOWS_APP_RELEASE_PATH: flutter_app\build\windows\x64\runner\Release
      WINDOWS_ZIP_NAME: thu_downloader.zip
      WINDOWS_INSTALLER_NAME: thu_downloader-${{ github.ref_name }}-windows-x86_64-installer
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action-win
        with:
          channel: stable
          cache: true
      - working-directory: flutter_app
        run: flutter build windows --release && ls build\windows\x64\runner\Release
      
      - name: Archive Asset
        uses: vimtor/action-zip@v1
        with:
          files: ${{ env.WINDOWS_APP_RELEASE_PATH }}\
          dest: ${{ env.WINDOWS_APP_RELEASE_PATH }}\${{ env.WINDOWS_ZIP_NAME }}
      
      - name: Copy installer config & icon file
        working-directory: flutter_app
        run: |
            cp scripts/windows_installer/* ../${{ env.WINDOWS_APP_RELEASE_PATH }}
      
      - name: Build installer executable
        working-directory: ${{ env.WINDOWS_APP_RELEASE_PATH }}
        run: |
          iscc /F${{ env.WINDOWS_INSTALLER_NAME }} inno_setup_config.iss /DAppVersion=0.0.1
      
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-win
          path: ${{ env.WINDOWS_INSTALLER_NAME }}


  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action-linux
        with:
          channel: stable
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      
      - working-directory: flutter_app
        run: flutter build linux --release && ls build/linux/x64/release/bundle/

      - name: Print outputs
        shell: bash
        run: |
          echo CACHE-PATH=${{ steps.flutter-action-linux.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action-linux.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action-linux.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action-linux.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action-linux.outputs.ARCHITECTURE }}
          echo PUB-CACHE-PATH=${{ steps.flutter-action-linux.outputs.PUB-CACHE-PATH }}
          echo PUB-CACHE-KEY=${{ steps.flutter-action-linux.outputs.PUB-CACHE-KEY }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-linux
          path: flutter_app/build/linux/x64/release/bundle/thu_downloader