name: flutter test
on: [push]
jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: cd flutter_app && flutter build macos --release --no-codesign
      

  win:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action-win
        with:
          channel: stable
          cache: true
      - run: cd flutter_app && flutter build windows
      
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-win
          path: flutter_app\build\windows\x64\runner\Release\flutter_thu_dowloader.exe
      - name: Print outputs
        shell: bash
        run: |
          echo CACHE-PATH=${{ steps.flutter-action-win.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action-win.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action-win.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action-win.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action-win.outputs.ARCHITECTURE }}
          echo PUB-CACHE-PATH=${{ steps.flutter-action-win.outputs.PUB-CACHE-PATH }}
          echo PUB-CACHE-KEY=${{ steps.flutter-action-win.outputs.PUB-CACHE-KEY }}

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action-linux
        with:
          channel: stable
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: cd flutter_app && flutter build linux

      - name: Print outputs
        shell: bash
        run: |
          echo CACHE-PATH=${{ steps.flutter-action-linux.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action-linux.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action-linux.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action-linux.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action-linux.outputs.ARCHITECTURE }}
          echo PUB-CACHE-PATH=${{ steps.flutter-action-linux.outputs.PUB-CACHE-PATH }}
          echo PUB-CACHE-KEY=${{ steps.flutter-action-linux.outputs.PUB-CACHE-KEY }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-linux
          path: flutter_app/build/linux/x64/release/bundle/thu_downloader