name: flutter test
on: [push]
jobs:
  # main:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: cd flutter_app && flutter build macos

  win:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action-win
        with:
          channel: stable
          cache: true
      - run: cd flutter_app && flutter build windows
      
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-win
          path: flutter_app\build\windows\x64\runner\Release\flutter_thu_dowloader.exe

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux